### PR TITLE
Introduce docker build for application

### PR DESCRIPTION
**Pull request by rounakdatta**

### CODE REVIEW

**Comment by pketh** [comment]
Thanks for the PR! I've never used docker, what problems does it solve?

**Comment by rounakdatta** [comment]
Hi,
- I think docker would be helpful in containerized deployment environments. For example, I deploy applications to my homelab [declaratively](https://github.com/rounakdatta/homelab.setup/blob/main/roles/launch-nomad-jobs/templates/audiobookshelf.nomad.j2) to a Nomad cluster, and instead of writing setup scripts, one could link the container image and get going.
- Another situation could be helping someone to quickly get this running on their local without bothering about their Node setup. All they'd need a `docker run -p 8080:8080 <>` command.

If we decide to go ahead with dockerized packaging for kinopio-client, just adding the Dockerfile wouldn't help, we'd need to set up GHA workflows to publish the container images as well. Happy to add and help with those as well. Thanks!

**Comment by pketh** [comment]
hey rounakdatta,

I'm cool with making it easier for people to deploy with docker if they so choose – so from my pov: 

- it should just be an optional way to deploy for people who choose to use it
- it doesn't change how the app is normally deployed to prod
- it should not require maintainance/support (at least from me lol)

this pr seems like it satisfies this. But to make sure, can you create a seperate `readme-docker.md` with the info/instructions that would be required of someone interested in using docker to set up? 

are the GHA workflows something that needs to be set up on this repo , or something that a forker would need to set up on their repos (so then it would be steps to add to readme-docker.md ?)

thx

**Comment by pketh** [comment]
requested in https://github.com/kinopio-club/kinopio-client/issues/530

**Comment by pketh** [comment]
closed due to inactivity, feel free to reopen if still interested

**Pull request closed without merging**
